#!/bin/bash

PGDATADIR=/dev/shm/$USER/pgdata
PGPORT=5432

BASEDIR=$(cd "$(dirname $0)"; pwd)
cd $BASEDIR
#pkill 'postgres|postmaster'
#sleep 2

PORTLIST="$(lsof -i tcp:$PGPORT | tail -n +2 | awk '{print $2}')"
if [[ $(echo "$PORTLIST" | wc -w) -gt 0 ]];
then
  echo "The following processes have taken port $PGPORT"
  echo "Please terminate them before running this script"
  echo
  for p in $PORTLIST;
  do
    ps -o pid,cmd
  done
  exit -1
fi

for i in $(seq 1 22);
do
 # echo "Starting the postgres server"
  perf record -g postgres -D $PGDATADIR &
  PGPID=$!
  sleep 2
  f="q$i.sql"
  cgf="../callgraph-q$i.pdf"
  echo "Running query: $i"
  psql tpch <$f
  pkill 'postgres|postmaster'
  sleep 2
  dir="perfdata-q$i"
  mkdir -p $dir
  mv perf.data $dir/
  cd $dir
  echo "Creating the call graph: $cgf"
  perf script | python $BASEDIR/gprof2dot.py -f perf | dot -Tpdf -o $cgf &
  cd - >/dev/null
done

for p in $(jobs -p);
do
  wait $p
done

